resume-controllers:
    resource:
        path: ../src/Resume/Transport/Controller/Api/
        namespace: App\Resume\Transport\Controller\Api
    type: attribute
    prefix: /api
    defaults:
        _format: json
